name: Update Spotify Top Tracks

on:
  schedule:
    # Ejecuta todos los días a las 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch:    # Permite dispararlo manualmente

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Fetch Spotify playlists
        env:
          CLIENT_ID:     ${{ secrets.SPOTIFY_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: node fetch_spotify_tracks.js

      - name: Commit and push updated JSON
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add spotify_top_tracks.json
          git diff --quiet || git commit -m "chore: daily update of top tracks"
          git push origin HEAD:main
